### ISSUE TITLE
[Bug]: Play local mp3-file

### ISSUE THREAD

**Issue by Berchemer** [iobroker-community-adapters/ioBroker.chromecast#105]
I read that this worked before in earlier versions of the adapter. Unfortunately it doesn't seem to work anymore with the current version 3.x.

For the future, it would be nice if the Chromecast adapter would also play local mp3 files (e.g. "/home/iobroker/mp3_files/sound01.mp3") by typing them into url2play.

**Comment by Berchemer** [comment]
After some testting I found following output of the chromecast adapter, if I want to play a local mp3.

The process can be easily reproduced:

The "chromecast.x.ID.player.play2url" object must be written with a local mp3 file (e.g. "/opt/iobroker/sayit.x/speech.mp3"), with "Acknowledged" set to false.

The Chromecast adapter will then output something similar to the text below if logging is set to debug.

I think this issue is the reason for the closed issue #106 of the sayit adapter [(https://github.com/ioBroker/ioBroker.sayit/issues/106)](https://github.com/ioBroker/ioBroker.sayit/issues/106)

Logfile - using a gooogle home mini:
`
2022-01-20 10:43:20.378 - debug: chromecast.0 (627079) Google_Home_Mini_-_2OG_-_Buero - device stateChange player.url2play {"val":"/opt/iobroker/sayit.x/007 - salamisound-6154324-glocke-anschlagen-einmal.mp3","ack":false,"ts":1642671800376,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1642671800376}
2022-01-20 10:43:20.378 - info: chromecast.0 (627079) %s - Not a http(s) URL -> asume local file for %s
2022-01-20 10:43:20.379 - debug: chromecast.0 (627079) 2OGBueroSpeaker - device stateChange player.url2play {"val":"/opt/iobroker/sayit.x/007 - salamisound-6154324-glocke-anschlagen-einmal.mp3","ack":false,"ts":1642671800376,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1642671800376}
2022-01-20 10:43:20.379 - info: chromecast.0 (627079) %s - Not a http(s) URL -> asume local file for %s
2022-01-20 10:43:20.383 - info: chromecast.0 (627079) Exported as http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia
2022-01-20 10:43:20.384 - info: chromecast.0 (627079) Google Home Mini - 2OG - Buero - Try to play url - http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia
2022-01-20 10:43:20.385 - info: chromecast.0 (627079) Google Home Mini - 2OG - Buero - Try to launch default player
2022-01-20 10:43:20.387 - info: chromecast.0 (627079) Exported as http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia
2022-01-20 10:43:20.388 - info: chromecast.0 (627079) 2OGBueroSpeaker - Try to play url - http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia
2022-01-20 10:43:20.389 - info: chromecast.0 (627079) 2OGBueroSpeaker - Try to launch default player
2022-01-20 10:43:20.391 - info: chromecast.0 (627079) Google Home Mini - 2OG - Buero - Closing mediaInfo
2022-01-20 10:43:20.391 - error: chromecast.0 (627079) Google Home Mini - 2OG - Buero - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:400:28)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-01-20 10:43:20.391 - error: chromecast.0 (627079) Google_Home_Mini_-_2OG_-_Buero - Cannot play file "http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
2022-01-20 10:43:20.395 - info: chromecast.0 (627079) 2OGBueroSpeaker - Closing mediaInfo
2022-01-20 10:43:20.396 - error: chromecast.0 (627079) 2OGBueroSpeaker - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:400:28)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-01-20 10:43:20.396 - error: chromecast.0 (627079) 2OGBueroSpeaker - Cannot play file "http://null:8082/state/chromecast.0.f0ef8673077c.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
`

and logfile while using a chromecast audio:
`
2022-01-20 10:45:18.784 - debug: chromecast.0 (627079) Chromecast_Audio_-_0OG_-_Treppenhaus - device stateChange player.url2play {"val":"/opt/iobroker/sayit.x/008 - salamisound-8157172-glocke-anschlagen-einmal.mp3","ack":false,"ts":1642671918782,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1642671918782}
2022-01-20 10:45:18.784 - info: chromecast.0 (627079) %s - Not a http(s) URL -> asume local file for %s
2022-01-20 10:45:18.785 - debug: chromecast.0 (627079) 0OGTreppenhausSpeaker - device stateChange player.url2play {"val":"/opt/iobroker/sayit.x/008 - salamisound-8157172-glocke-anschlagen-einmal.mp3","ack":false,"ts":1642671918782,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1642671918782}
2022-01-20 10:45:18.785 - info: chromecast.0 (627079) %s - Not a http(s) URL -> asume local file for %s
2022-01-20 10:45:18.791 - info: chromecast.0 (627079) Exported as http://null:8082/state/chromecast.0.546009e0744e.exportedMedia
2022-01-20 10:45:18.792 - info: chromecast.0 (627079) Chromecast Audio - 0OG - Treppenhaus - Try to play url - http://null:8082/state/chromecast.0.546009e0744e.exportedMedia
2022-01-20 10:45:18.792 - info: chromecast.0 (627079) Chromecast Audio - 0OG - Treppenhaus - Try to launch default player
2022-01-20 10:45:18.794 - info: chromecast.0 (627079) Exported as http://null:8082/state/chromecast.0.546009e0744e.exportedMedia
2022-01-20 10:45:18.794 - info: chromecast.0 (627079) 0OGTreppenhausSpeaker - Try to play url - http://null:8082/state/chromecast.0.546009e0744e.exportedMedia
2022-01-20 10:45:18.795 - info: chromecast.0 (627079) 0OGTreppenhausSpeaker - Try to launch default player
2022-01-20 10:45:18.798 - info: chromecast.0 (627079) Chromecast Audio - 0OG - Treppenhaus - Closing mediaInfo
2022-01-20 10:45:18.799 - error: chromecast.0 (627079) Chromecast Audio - 0OG - Treppenhaus - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:400:28)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-01-20 10:45:18.799 - error: chromecast.0 (627079) Chromecast_Audio_-_0OG_-_Treppenhaus - Cannot play file "http://null:8082/state/chromecast.0.546009e0744e.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
2022-01-20 10:45:18.800 - info: chromecast.0 (627079) 0OGTreppenhausSpeaker - Closing mediaInfo
2022-01-20 10:45:18.801 - error: chromecast.0 (627079) 0OGTreppenhausSpeaker - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:400:28)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-01-20 10:45:18.801 - error: chromecast.0 (627079) 0OGTreppenhausSpeaker - Cannot play file "http://null:8082/state/chromecast.0.546009e0744e.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
`

**Comment by raintonr** [comment]
This is working here using latest master. Have you tried using that?

**Comment by haselchen** [comment]
Ich bekomme , mit egal welcher Version, keine mp3 mehr abgespielt. Bekomme ewig den Error...**could not upload**....
Keine Chance, egal welche URL ich da eingebe.
Hat jemand eine Erleuchtung?

**Comment by raintonr** [comment]
> Ich bekomme , mit egal welcher Version, keine mp3 mehr abgespielt. Bekomme ewig den Error...**could not upload**.... Keine Chance, egal welche URL ich da eingebe. Hat jemand eine Erleuchtung?

**Local** MP3. You cannot enter a URL, just a location on the local filesystem.

**Comment by haselchen** [comment]
Ok, falsch ausgedrückt. Mit URL meinte ich alle Möglichkeiten eines lokalen Pfades.

**Comment by raintonr** [comment]
> Ok, falsch ausgedrückt. Mit URL meinte ich alle Möglichkeiten eines lokalen Pfades.

What O/S are you using? What value did you place in the `url2play` state?

**Comment by Berchemer** [comment]
> This is working here using latest master. Have you tried using that?

I wrote `'/media/iobroker/136_www/temp/google.mp3'` into url2play.

I reinstalled the v3.0.1 directly from Github on 08.03.2022.
It just doesn't work because the adapter recognizes a local file but tries to generate a URL from it that is completely broken 😢

As I wrote before here the Error-Log:

`2022-03-08 16:34:23.092 - info: chromecast.0 (114438) Chromecast Audio - 1OG - Schlafzimmer - setting volume to same value 30 - ignored
2022-03-08 16:34:23.094 - info: chromecast.0 (114438) 1OGSchlafzimmerSpeaker - setting volume to same value 30 - ignored
2022-03-08 16:34:23.099 - info: chromecast.0 (114438) %s - Not a http(s) URL -> asume local file for %s
2022-03-08 16:34:23.106 - info: chromecast.0 (114438) %s - Not a http(s) URL -> asume local file for %s

2022-03-08 16:34:23.187 - info: chromecast.0 (114438) Exported as http://null:8082/state/chromecast.0.A.exportedMedia
2022-03-08 16:34:23.188 - info: chromecast.0 (114438) Chromecast Audio - 1OG - Schlafzimmer - Try to play url - http://null:8082/state/chromecast.0.A.exportedMedia
2022-03-08 16:34:23.209 - info: chromecast.0 (114438) Chromecast Audio - 1OG - Schlafzimmer - Try to launch default player
2022-03-08 16:34:23.221 - info: chromecast.0 (114438) Chromecast Audio - 1OG - Schlafzimmer - Closing mediaInfo
2022-03-08 16:34:23.225 - error: chromecast.0 (114438) Chromecast Audio - 1OG - Schlafzimmer - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:400:28)
at Socket.socketErrorListener (_http_client.js:475:9)
at Socket.emit (events.js:400:28)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-03-08 16:34:23.227 - error: chromecast.0 (114438) Chromecast_Audio_-_1OG_-_Schlafzimmer - Cannot play file "http://null:8082/state/chromecast.0.A.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
2022-03-08 16:34:23.236 - info: chromecast.0 (114438) Exported as http://null:8082/state/chromecast.0.A.exportedMedia
2022-03-08 16:34:23.237 - info: chromecast.0 (114438) 1OGSchlafzimmerSpeaker - Try to play url - http://null:8082/state/chromecast.0.A.exportedMedia
2022-03-08 16:34:23.240 - info: chromecast.0 (114438) 1OGSchlafzimmerSpeaker - Try to launch default player
2022-03-08 16:34:23.242 - info: chromecast.0 (114438) Exported as http://null:8082/state/chromecast.0.A.exportedMedia`

**Comment by raintonr** [comment]
What does the adapter instance config screen look like? What have you set web instance and web server IP to?

**Comment by Berchemer** [comment]
> What does the adapter instance config screen look like? What have you set web instance and web server IP to?

Config-windows only gives me the choise of web-instance where I chose `"web.0"`.
Inside the adpter web.0 the correct IP of the iobroker installation is chosen.
Everything else using the same web-adapter also works without problems.
I only don't know what the extra-setting `'Redirect options'` inside the web-adapter is used for.
This is left empty in my installation and seems to use the `'Default redirect path'`.
Whatever that means 😉

Btw.: The same file with same config but called by `'http://192.X.X.60/Sounds/temp/google.mp3'` (which is the same file as `'/media/iobroker/136_www/temp/google.mp3'` ) is mostly played correct by the adapter.

**Comment by raintonr** [comment]
> Config-windows only gives me the choise of web-instance where I chose `"web.0"`.

Are you sure you are not using outdated version of web or chromecast adapter then? My chromcast adapter config screen has both 'Web instance' and 'Web server IP' settings. 

See this error in your log above:

```
2022-03-08 16:34:23.187 - info: chromecast.0 (114438) Exported as http://null:8082/state/chromecast.0.A.exportedMedia
```

Shows the obvious error that IP address is `null`. Seems this would be read from the config screen option you say does not exist. If your config screen is outdated you could try `iob upload chromecast` to refresh it?

**Comment by Berchemer** [comment]
I stopped the chromecast adapter inside iobroker.
Logged in by putty, changed to /opt/iobroker and called  `iob upload chromecast`
The settings windows only shows as attached:
![2022-03-09 - 09_19 - chromecast settings](https://user-images.githubusercontent.com/44316663/157400995-7df9fdc1-8a20-4b2d-a5bd-940ad907e06b.PNG)

**Comment by raintonr** [comment]
That seems to be your problem then. But why?

What other adapters do you have? Do you have instances of discovery & net-tools? I notice that recently chromecast changed to require net-tools (which needs discovery).

**Comment by Berchemer** [comment]
> That seems to be your problem then. But why?
> 
> What other adapters do you have? Do you have instances of discovery & net-tools? I notice that recently chromecast changed to require net-tools (which needs discovery).

I have a lot 😉
Yes discovery and net-tools are installed and activated.
Discovery was not activated before, but now is.

I changed to beta-Status and updated all I could find.
But...
The same windows in the instance settings of the chromecast adapter. Only one field to choose, where I have chosen web.0 🤷‍♂️

And adding a local file to play2url causes again following error-output:
```
2022-03-09 11:04:33.864  - [34mdebug[39m: chromecast.0 (3242) 1OGSchlafzimmerSpeaker - device stateChange player.url2play {"val":"/media/iobroker/136_www/temp/google.snd.26c1dea3-b1f7-4298-8dc0-4c2983917901.mp3","ack":false,"ts":1646820273862,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1646820069321}
2022-03-09 11:04:33.865  - [32minfo[39m: chromecast.0 (3242) %s - Not a http(s) URL -> asume local file for %s
2022-03-09 11:04:33.871  - [32minfo[39m: chromecast.0 (3242) Exported as http://null:8082/state/chromecast.0.XXSerialNumberXX.exportedMedia
2022-03-09 11:04:33.871  - [32minfo[39m: chromecast.0 (3242) 1OGSchlafzimmerSpeaker - Try to play url - http://null:8082/state/chromecast.0.XXSerialNumberXX.exportedMedia
2022-03-09 11:04:33.875  - [32minfo[39m: chromecast.0 (3242) 1OGSchlafzimmerSpeaker - Closing mediaInfo
2022-03-09 11:04:33.876  - [31merror[39m: chromecast.0 (3242) 1OGSchlafzimmerSpeaker - Error playing playlist - Error: Error: getaddrinfo EAI_AGAIN null
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-03-09 11:04:33.876  - [31merror[39m: chromecast.0 (3242) 1OGSchlafzimmerSpeaker - Cannot play file "http://null:8082/state/chromecast.0.XXSerialNumberXX.exportedMedia": Error: Error: getaddrinfo EAI_AGAIN null
```

**Comment by Berchemer** [comment]
> That seems to be your problem then. But why?
> 
> What other adapters do you have? Do you have instances of discovery & net-tools? I notice that recently chromecast changed to require net-tools (which needs discovery).

Is there maybe a file I can just replace on mine to have the necessary data or can I edit a file to add the missing IP address there?
There is simply no field to enter anything other than web.0.
Or do I have to enter the IP there???
Or is it maybe a problem with the web-adapter???
Or could you show me the place inside the adapter-source where I could add the IP manually for testing purposes?

**Comment by Berchemer** [comment]
Too bad.
I just thought if I edit the line 884 of the file

`/opt/iobroker/node_modules/iobroker.chromecast/libchromecastDevice.js`

and manually add the IP address of the host

`url2play = 'http://192.X.Y.Z:8082/state/' + exported_file_state;`
instead of 
`url2play = 'http://' + adapter.config.webServer + ':8082/state/' + exported_file_state;`

I could force the output to a local file.

Unfortunately it didn't work.

After making changes to the files below /opt/iobroker/ do you have to call something else so that the changes made are also accepted?
Or do you have to reboot the computer with ioBroker?

**Comment by Berchemer** [comment]
> On that topic, I have 2 web adapters running, do you? Maybe the IP address config only shows when there is more than one to choose?

Strange.
I now have a second instance of the web adapter installed. This instance is installed but disabled.
In the ChromeCast adapter, I select the disabled instance because this selection also shows an input field for the IP address.
Now the output of local mp3 files works.
I don't understand that, do I ?

**Comment by raintonr** [comment]
So just adding a second web adapter is a workaround for this bug?

**Comment by Berchemer** [comment]
No. It seems that the output of a non local file is not possible anymore... By now I don't know where to change which settings to get the chromecast adapter to play an http:// sound :-(
I am working on that but I think the Adapter is yet a litte bit $%§ööü?ä!

**Comment by raintonr** [comment]
> No. It seems that the output of a non local file is not possible anymore... 

That is not true. I use it every day here. v3.0.1.

**Comment by Berchemer** [comment]
> > No. It seems that the output of a non local file is not possible anymore...
> 
> That is not true. I use it every day here. v3.0.1.

Sorry I think you misunderstood me 😉
I meant that the local output didn't work for me anymore after making changes to the different web-adapter-instances- and the chromecast-configurations.
Now the output of local files works again but this can't hide that there are some more probölems with the chromecast-adapter. Why do I need to install to instances of the web adapter to get the chromecast adapter playing local files???

I would really be happy if in the future the problems with sound-output inside ioBroker would be solved generally. It is not only the chromecast. Also the sons-adapter seems to make problems.

But as I said before. I don't know why but now my ioBroker plays local mp3 files with the sonos and chromecast adapters.
That's enough for me for the moment 😁
Thanks for giving hints to solve my problems 👍

**Comment by raintonr** [comment]
> ...I meant that the local output didn't work for me anymore after making changes to the different web-adapter-instances- and the chromecast-configurations.

So the adapter is still broken? Erm...?

> Now the output of local files works again...

... or not?

Please tell us **exactly** what you did to make things work. If a bug cannot be described and replicated it is very hard to fix.

For example, if things are working now, undo what you did - does it stop working? Change your installation once more (tell us **exactly** what do you) - does it start working? If yes, cool - these are great clues to find the bug.

**Comment by maxpd1** [comment]
would also be interested in the correct solution

**Comment by divY42** [comment]
I am currently having the same issue.

> > After making changes to the files below /opt/iobroker/ do you have to call something else so that the changes made are also accepted? Or do you have to reboot the computer with ioBroker?
> 
> You need to restart the adapter is all. I still think you should concentrate on why the value of `adapter.config.webServer` is null.
> 
> On that topic, I have 2 web adapters running, do you? Maybe the IP address config only shows when there is more than one to choose?

adapter.config.webServer seems to be null. Using a second web server instance does nothing for me.
I cannot edit or select a proper IP adress in the chromecast adapter settings.

![image](https://user-images.githubusercontent.com/47355195/211417548-d624d4d0-ba54-4b7f-a16e-e785b31454c4.png)

This is the configuration for my web.0 instance:

![image](https://user-images.githubusercontent.com/47355195/211417676-59a4a8f8-4cfd-49db-a16f-4efc63afcef1.png)

Any ideas what I can try to get rid of this error?
discovery and net-tools are running as well.

**Comment by raintonr** [comment]
What version of the adapter? Latest master works perfectly here.

**Comment by divY42** [comment]
I'm using v3.0.3

**Comment by raintonr** [comment]
I notice in your logs trying to play with null server details. It's as if you haven't selected a web server in the config, but you say you have. Then I notice there's no IP address next to the server. That's probably the issue.

**Comment by divY42** [comment]
yeah I know that is the issue.
My whole comment is about that I can't select an IP adress there :D

**Comment by raintonr** [comment]
So why didn't you raise an issue with "Cannot select IP address for web instance"? :disappointed:

**Comment by divY42** [comment]
because the issue discussed here had the same problems (null URL, not able to select an IP adress for web instance), why bother with an additional issue?

**Comment by raintonr** [comment]
But you notice this bug is closed. Please raise a new one.

**Comment by divY42** [comment]
ok, I will do that. no hard feelings, I thought it would be better that way :)
