### ISSUE TITLE
[Bug]: TypeError: Cannot use 'in' operator to search for 'content-type' in undefined

### ISSUE THREAD

**Issue by aortmannm** [iobroker-community-adapters/ioBroker.chromecast#123]
### What happened?

I updated Node to version 16 and npm to 8 because it's now the way to go for ioBroker.

With the new node version it doesn't seem to work anymore.

I used url2play to play online radio and now I get these errors:

```
chromecast.0 | 2022-06-20 08:09:37.362 | error | Alle - Cannot play file "https://liveradio.swr.de/sw282p3/dasding/play.mp3": TypeError: Cannot use 'in' operator to search for 'content-type' in undefined

chromecast.0 | 2022-06-20 08:09:37.359 | error | Alle - Error playing playlist - TypeError: Cannot use 'in' operator to search for 'content-type' in undefined at MediaInfo._parseIcyHeaderPromise (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:143:26) at /opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:47:43 at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 1)
```

### Adapter Version

3.0.1

### JS-Controller Version

4.0.23

### Node JS Version

16.15.1

### NPM Version

8.11.0

### Operating System

Debian

### Relevant log output

```shell
chromecast.0 | 2022-06-20 08:09:37.362 | error | Alle - Cannot play file "https://liveradio.swr.de/sw282p3/dasding/play.mp3": TypeError: Cannot use 'in' operator to search for 'content-type' in undefined

chromecast.0 | 2022-06-20 08:09:37.359 | error | Alle - Error playing playlist - TypeError: Cannot use 'in' operator to search for 'content-type' in undefined at MediaInfo._parseIcyHeaderPromise (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:143:26) at /opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:47:43 at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 1)
```

**Comment by Apollon77** [comment]
duplicate #124??

**Comment by aortmannm** [comment]
Yes this is a duplicate
