### ISSUE TITLE
[Bug]: Socket hang up

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.chromecast#159]
### What happened?

A bug happened!

When playing an audio via sayit adapter on google Chrome I receive this log without any audio output.
It worked before but since weeks the actual audio output was often minutes behind the announcement beep.
Now there is no output anymore with this error

```
2023-04-04 17:31:40.846 - info: sayit.3 (4669) saying: Denk dran Fenster im Wohnzimmer zu schließen. Sonst wird's kalt im Haus. Die Heizung wurde schon abgedreht
--
2023-04-04 17:31:40.860 - info: sayit.3 (4669) Set "chromecast.0.groups.ce448fca3cc1d12f5b76b2a.player.announcement to {"url":"/state/sayit.3.tts.mp3","volume":100}
2023-04-04 17:31:40.877 - info: chromecast.0 (4689) Iobrokergruppe - Try to launch default player
2023-04-04 17:31:40.971 - info: chromecast.0 (4689) Update client status: Büro
2023-04-04 17:31:40.972 - info: chromecast.0 (4689) Büro - Try to join player
2023-04-04 17:31:40.974 - info: chromecast.0 (4689) Büro - Connected player
2023-04-04 17:31:40.978 - info: chromecast.0 (4689) Büro - Player joint
2023-04-04 17:31:41.032 - info: chromecast.0 (4689) Update client status: Küche
2023-04-04 17:31:41.034 - info: chromecast.0 (4689) Küche - Try to join player
2023-04-04 17:31:41.036 - info: chromecast.0 (4689) Küche - Connected player
2023-04-04 17:31:41.037 - info: chromecast.0 (4689) Küche - Player joint
2023-04-04 17:31:41.114 - info: chromecast.0 (4689) Büro - getStatus
2023-04-04 17:31:41.146 - info: chromecast.0 (4689) Küche - getStatus
2023-04-04 17:31:41.684 - info: chromecast.0 (4689) Update client status: Büro
2023-04-04 17:31:41.688 - info: chromecast.0 (4689) Update client status: Küche
2023-04-04 17:31:43.487 - info: chromecast.0 (4689) Update client status: Büro
2023-04-04 17:31:43.489 - info: chromecast.0 (4689) Update client status: Küche
2023-04-04 17:31:43.596 - info: chromecast.0 (4689) Update client status: Badezimmer
2023-04-04 17:31:43.644 - info: chromecast.0 (4689) Update client status: Iobrokergruppe
2023-04-04 17:31:43.645 - info: chromecast.0 (4689) Iobrokergruppe - Try to join player
2023-04-04 17:31:43.647 - info: chromecast.0 (4689) Iobrokergruppe - Connected player
2023-04-04 17:31:43.648 - info: chromecast.0 (4689) Iobrokergruppe - Default player lauched
2023-04-04 17:31:43.649 - info: chromecast.0 (4689) Iobrokergruppe - Connected player
2023-04-04 17:31:43.650 - info: chromecast.0 (4689) Iobrokergruppe - Player joint
2023-04-04 17:31:43.650 - info: chromecast.0 (4689) Iobrokergruppe - Try to play announcement - "/state/sayit.3.tts.mp3"
2023-04-04 17:31:43.651 - info: chromecast.0 (4689) Iobrokergruppe - Try to play url - /state/sayit.3.tts.mp3
2023-04-04 17:31:43.663 - info: chromecast.0 (4689) Iobrokergruppe - Closing mediaInfo
2023-04-04 17:31:43.667 - error: chromecast.0 (4689) Iobrokergruppe - Error playing playlist - Error: Error: socket hang up
```

### Adapter Version

3.0.3

### JS-Controller Version

4.0.23

### Node JS Version

14.21.3

### NPM Version

6.14.18

### Operating System

Debian

**Comment by raintonr** [comment]
What is 'Iobrokergruppe'? I assume it's  player group, right? Please try using an individual player and let us know if this error is limited to groups or happens on all player types.

**Comment by maxpd1** [comment]
Correct. It is a group of speakers.
It also happens if only one speaker is addressed

**Comment by maxpd1** [comment]
I updated Nodejs, jscontroler and the hole system.
I thought about last changes I did and I think it was activation of https in web adapter.

Without https in web adapter I receive now this error message in chromecast:

`<html>
<body>


chromecast.0 | 2023-04-12 20:40:40.053 | error | Wohnzimmer - Could not play announcement: Error: Error: write EPROTO C0DAF3B6:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
-- | -- | -- | --
chromecast.0 | 2023-04-12 20:40:40.052 | error | Wohnzimmer - Error playing playlist - Error: Error: write EPROTO C0DAF3B6:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355: at ClientRequest.<anonymous> (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:81:98) at ClientRequest.emit (node:events:525:35) at ClientRequest.emit (node:domain:489:12) at TLSSocket.socketErrorListener (node:_http_client:502:9) at TLSSocket.emit (node:events:513:28) at TLSSocket.emit (node:domain:489:12) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at processTicksAndRejections (node:internal/process/task_queues:82:21)


</body>
</html>`

With https and default public key

`<html>
<body>


chromecast.0 | 2023-04-12 20:45:10.162 | error | Wohnzimmer - Could not play announcement: Error: Error: self-signed certificate
-- | -- | -- | --
chromecast.0 | 2023-04-12 20:45:10.162 | error | Wohnzimmer - Error playing playlist - Error: Error: self-signed certificate at ClientRequest.<anonymous> (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:81:98) at ClientRequest.emit (node:events:525:35) at ClientRequest.emit (node:domain:489:12) at TLSSocket.socketErrorListener (node:_http_client:502:9) at TLSSocket.emit (node:events:513:28) at TLSSocket.emit (node:domain:489:12) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at processTicksAndRejections (node:internal/process/task_queues:82:21)


</body>
</html>`
