### ISSUE TITLE
Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26

### ISSUE THREAD

**Issue by ralpha1983** [iobroker-community-adapters/ioBroker.chromecast#175]
### Contact Details

ralph@keewee.ch

### What happened?

Since I updated the adapter to the last Version 3.0.3, every Night i get Warnings in ioBroker Protocolls.
![Screenshot 2023-07-20 093602](https://github.com/iobroker-community-adapters/ioBroker.chromecast/assets/85409213/763dcc80-0fe2-4f58-b8a8-8168ec4134e0)

### Adapter Version

3.0.3

### JS-Controller Version

4.0.24

### Node JS Version

16.19.0

### NPM Version

8.19.3

### Operating System

Ubuntu

### Relevant log output

```shell
2023-07-20 04:51:29.558 - info: chromecast.0 (655950) UG Keller - client disconnected
2023-07-20 04:51:29.564 - warn: chromecast.0 (655950) UG Keller - Client error: Error: connect ECONNREFUSED 192.158.3.109:8009
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
2023-07-20 04:51:30.569 - warn: chromecast.0 (655950) UG Keller - Client error: Error: connect ECONNREFUSED 192.158.3.109:8009
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
2023-07-20 04:51:32.573 - warn: chromecast.0 (655950) UG Keller - Client error: Error: connect ECONNREFUSED 192.158.3.109:8009
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
2023-07-20 04:51:38.175 - info: chromecast.0 (655950) Received keep alive for disconnected device UG Keller
2023-07-20 04:51:38.175 - info: chromecast.0 (655950) Reconnecting UG Keller to 192.158.3.109:8009
2023-07-20 04:51:39.080 - warn: chromecast.0 (655950) UG Keller - Client error: Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by raintonr** [comment]
What client device is this? Is it on the same subnet as your IoB instance?

**Comment by ralpha1983** [comment]
It concerns Google Mini / Nest Mini. All three Mini’s are in the same subnet as ioBroker.

 

Von: Robin Rainton ***@***.***> 
Gesendet: Freitag, 21. Juli 2023 12:06
An: iobroker-community-adapters/ioBroker.chromecast ***@***.***>
Cc: ralpha1983 ***@***.***>; Author ***@***.***>
Betreff: Re: [iobroker-community-adapters/ioBroker.chromecast] Client error: Error: Device timeout at fn.ontimeout (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:56:26 (Issue #175)

 

What client device is this? Is it on the same subnet as your IoB instance?
