### ISSUE TITLE
[Bug]: Chromecast crashes in cause of using Chromecast Built in in Sony XH90

### ISSUE THREAD

**Issue by M1cS0w** [iobroker-community-adapters/ioBroker.chromecast#97]
### Contact Details

m1cs0w@online.de

### What happened?

Using a Sony XH90 television let crashes the ChromeCast Adapter in iobroker.

### Adapter Version

2.3.1

### JS-Controller Version

3.3.18

### Node JS Version

12.22.6

### NPM Version

6.14.15

### Operating System

Debian

### Relevant log output

```shell
<html>
<body>
<!--StartFragment-->

host.debian | 2021-09-21 00:35:41.710 | error | instance system.adapter.chromecast.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
chromecast.0 | 2021-09-21 00:35:41.159 | error | Cannot read property 'contentId' of undefined
chromecast.0 | 2021-09-21 00:35:41.159 | error | TypeError: Cannot read property 'contentId' of undefined at PersistentPlayer._playerStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58) at DefaultMediaReceiver.emit (events.js:314:20) at fn.onstatus (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10) at fn.emit (events.js:314:20) at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12) at fn.emit (events.js:326:22) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:314:20) at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10) at Client.emit (events.js:326:22)
chromecast.0 | 2021-09-21 00:35:41.158 | error | uncaught exception: Cannot read property 'contentId' of undefined
host.debian | 2021-09-21 00:34:10.534 | error | instance system.adapter.chromecast.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
chromecast.0 | 2021-09-21 00:34:09.983 | error | Cannot read property 'contentId' of undefined
chromecast.0 | 2021-09-21 00:34:09.983 | error | TypeError: Cannot read property 'contentId' of undefined at PersistentPlayer._playerStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58) at DefaultMediaReceiver.emit (events.js:314:20) at fn.onstatus (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10) at fn.emit (events.js:314:20) at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12) at fn.emit (events.js:326:22) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:314:20) at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10) at Client.emit (events.js:326:22)
chromecast.0 | 2021-09-21 00:34:09.982 | error | uncaught exception: Cannot read property 'contentId' of undefined
host.debian | 2021-09-21 00:32:58.302 | error | instance system.adapter.chromecast.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
chromecast.0 | 2021-09-21 00:32:57.748 | error | Cannot read property 'contentId' of undefined
chromecast.0 | 2021-09-21 00:32:57.747 | error | TypeError: Cannot read property 'contentId' of undefined at PersistentPlayer._playerStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58) at DefaultMediaReceiver.emit (events.js:314:20) at fn.onstatus (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10) at fn.emit (events.js:314:20) at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12) at fn.emit (events.js:326:22) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:314:20) at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10) at Client.emit (events.js:326:22)
chromecast.0 | 2021-09-21 00:32:57.747 | error | uncaught exception: Cannot read property 'contentId' of undefined

<!--EndFragment-->
</body>
</html>
```
```


### Anything else?

_No response_

**Comment by Jey-Cee** [comment]
Same as #95
